
execute pathogen#infect()

set bg=dark

set incsearch
set hlsearch

set scrolljump=5
set sidescrolloff=5
set scrolloff=3

set dir=~/tmp
set sm
set nobackup
set history=50

set laststatus=2

set backspace=start,eol,indent

set expandtab
set ts=4
set sw=4

set modeline

syntax on
filetype plugin indent on

colorscheme desert256
"let g:zenburn_high_Contrast=1
"colorscheme zenburn
"colorscheme 256-grayvim
"colorscheme symfony
"colorscheme jellybeans

let g:ctrlp_max_files = 0
let g:ctrlp_follow_symlinks = 1
let g:ctrlp_max_height = 20
"" use the current directory first
let g:ctrlp_working_path_mode = 'wr'
let g:ctrlp_clear_cache_on_exit = 1
""let g:ctrlp_lazy_update = 1
let g:ctrlp_regexp = 1
let g:ctrlp_custom_ignore = {
    \ 'dir': '\v(vendor.*vendor$|web$|.*/tests$|.*/cache$|.*/storage$|.*/_fixtures$|.*/coverage$)',
    \ 'file': '\v(.*debug.js|.*coverage.js|.*min.js|.*min.css)'
\ }
""let g:ctrlp_user_command = [ 'ezpublish/console',  '/home/dp/.vim/shell/locate.sh %s']
" TODO: custom index file for projects

"let g:unite_source_file_rec_max_cache_files=100000
"call unite#custom#source("file_rec/async", "ignore_pattern", ".*/cache/\\|.*/vendor/.*/vendor/\\|.*/zetacomponents/.*/tests\\|*./storage/\\|.*coverage.js\\|.*debug.js\\|.*/_fixtures")
"call unite#filters#matcher_default#use(['matcher_glob'])
"nnoremap <C-p> :Unite -start-insert file_rec/async:!<cr>
"nnoremap <C-g> :Unite grep:.<cr>

set tags=~/.cache/tags

map <F2> :NERDTreeToggle<CR>
map <F3> :TagbarToggle<CR>

cnoremap w!! w !sudo tee % >/dev/null
map \ :nohlsearch<CR>

set pastetoggle=<ins>
nnoremap <silent> <ins> :setlocal paste!<CR>i
autocmd InsertLeave <buffer> se nopaste

autocmd VimLeavePre * :mksession! ~/tmp/stopped.vim

au BufRead,BufNewFile *.twig        set filetype=jinja
au BufRead,BufNewFile *.html.twig   set filetype=htmljinja
au BufRead,BufNewFile *.swig        set filetype=htmljinja

au BufRead,BufNewFile *.md  set ft=markdown

hi LineNr ctermbg=235
hi ColorColumn ctermbg=233
hi Pmenu ctermbg=233 ctermfg=7
