#! /bin/bash

export NO_AT_BRIDGE=1
export PATH=~/bin:$PATH
#export OOO_FORCE_DESKTOP="gnome"
xcompmgr -l 0 -t 0 -C &
gnome-screensaver &
stalonetray --dockapp-mode simple -i 32 --slot-size 40 -p &
sh .fehbg
xrdb .Xdefaults &
cbatticon &
tdc --enable-cal &
xset b off

env > ~/.env.log

#xscreensaver -no-splash &
#conky -c .conkybar | ~/bin/lemonbar -g 600x25 -B '#cc000000' -F '#fff' -f 'Tahoma:size=9' -f 'Font Awesome:size=10' | sh &
#gnome-power-manager &
#mpd ~/.mpd.conf
#urxvt -e irssi &

#pidgin &
#skypeforlinux &
#update-notifier &

#fbpanel &
#nm-applet &
#cbatticon -l 10 -r 5 -x battery_notify.sh -n -i symbolic -c battery_notify.sh &
#empathy -h &
#gnome-volume-control-applet &
#skype &
#ario -m &
#conky  -p 5 -d
#numlockx on
