#! /bin/bash

export NO_AT_BRIDGE=1
export PATH=~/bin:$PATH
#export OOO_FORCE_DESKTOP="gnome"
xcompmgr -l 0 -t 0 -C &
gnome-screensaver &
dunst &
stalonetray --dockapp-mode simple -i 32 --slot-size 40 &
sh .fehbg
xrdb .Xdefaults &
cbatticon & # TODO notify
# remove the middle click on the pad
# xinput set-button-map 11 1 1 3 4 5 6 7
xset b off

xprofile
spotify &
firefox &
x-terminal-emulator &

notify-info &


env > ~/.env.log
