#! /bin/bash

export NO_AT_BRIDGE=1
export PATH=~/bin:$PATH
sh .fehbg
gnome-screensaver &
dunst &
stalonetray --dockapp-mode simple -i 32 --slot-size 40 &
xrdb .Xdefaults &
cbatticon & # TODO notify

# remove the middle click on the pad
xinput set-button-map "SynPS/2 Synaptics TouchPad" 1 1 3 4 5 6 7
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Accel Speed" 0.6
xinput --set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1

xset b off

xprofile
spotify &
firefox &
x-terminal-emulator &
one-slack &

notify-info &

one-monitoring &
compositor &

env > ~/.env.log
